default_language_version:
  python: python3.9

repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
- repo: https://github.com/timothycrosley/isort
  rev: 5.5.2
  hooks:
    - id: isort
      args:
        - "--check"
        - "--diff"
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      args:
        - "--check"
        - "--diff"
- repo: https://github.com/mgedmin/check-manifest
  rev: "0.43"
  hooks:
    - id: check-manifest
