name: Build and publish docs to GitHub Pages

on:
  push:
    branches:
      # TODO: change to "master" before merging
      - feature-docs

jobs:
  publish:
    env:
      OUTPUT_PATH: _build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up latest Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]

      - name: Generate HTML from Sphinx docs
        run: |
          # run HTML builder (-b) in nitpicky mode (-n) in a fresh environment (-E)
          sphinx-build -b html -n -E docs ${{ env.OUTPUT_PATH }}

      - name: Upload generated HTML as build artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ env.OUTPUT_PATH }}
          name: docs

      - name: Deploy generated HTML to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{ env.OUTPUT_PATH }}
          SINGLE_COMMIT: true
