name: Build and publish docs to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    env:
      OUTPUT_PATH: _build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Set up latest Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]

      - name: Generate HTML from Sphinx docs
        run: |
          # run HTML builder (-b) in nitpicky mode (-n) in a fresh environment (-E),
          # saving cached doctrees to a separate directory (-d)
          sphinx-build -b html -n -E -d .doctrees docs ${{ env.OUTPUT_PATH }}

      - name: Upload generated HTML as build artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.OUTPUT_PATH }}
          name: docs

      - name: Deploy generated HTML to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: ${{ env.OUTPUT_PATH }}
          single-commit: true
